version: "3"

services:
  aws-local-apigateway:
    image: lbernardo12/awslocal
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Set project path
      - .:/var/app
    environment:
      - VOLUME=$PWD # Source project path [required]
      - HOST=0.0.0.0
      - PORT=3001
      - ENVFILE=.env
    entrypoint: ["awslocal","api-gateway","--volume","$VOLUME","--port","3001"]
  aws-local-s3:
    image: lbernardo12/awslocal
    ports:
      - 3002:3002
    volumes:
      - /var/www/lbernardo/mybucket:/var/mystorage
      # Set project path
      - .:/var/app
    entrypoint: ["awslocal","s3","--volume","/var/mystorage"]