version: "3"

services:
  aws-local-apigateway:
    image: lbernardo12/aws-local-apigateway
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/local/LATAM-EIG/lbernardo/workspace/aws-local/example/go:/var/app
      # Set project path
      #- .:/var/app
    environment:
      - VOLUME=/home/local/LATAM-EIG/lbernardo/workspace/aws-local/example/go # Source project path [required]
      - HOST=0.0.0.0
      - PORT=3001
      - ENVFILE=.env
